done
sasha370/tincknetica-rack pull request #1
Opened 2020-12-08 12:59 UTC by sasha370

2020-12-08 20:03 UTC, BubuntuClu requested changes

2020-12-08 20:03 UTC, BubuntuClu commented on app.rb
> +    request = Rack::Request.new(env)
Rack приложение
Это данный класс. В его обязанности входит обработка запроса и формирование ответа в формате совместимом с rack. То есть здесь мы проверяем правильный ли пришёл URL или нужно отдать 404, хватает ли параметров или нужно отдать 400-й статус. При этом логику формирования тела ответа мы помещаем в отдельный класс бизнес логики.

Класс бизнес логики
Это отдельный простой Ruby класс, который может называться, например, TimeFormatter. Он ничего не должен знать о rack приложении, иными словами о том кто и где будет его использовать. Мы можем вызывать его из консоли или в другом Ruby приложении без HTTP API интерфейса.

2020-12-08 20:03 UTC, BubuntuClu commented on app.rb
> +    return status_404 unless route_present?(request)
оставляй пустую строку после `return`, сейчас это просто стена текста, где внутри запрятан return. читается плохо

2020-12-08 20:03 UTC, BubuntuClu commented on log/app.log
> +# Logfile created on 2020-12-08 16:56:07 +0300 by logger.rb/v1.4.2
логи всегда стоит помещать в гитигнор. другим разработчиком они не нужны

2020-12-08 20:03 UTC, BubuntuClu commented on app.rb
> +    [400, headers, ["Unknown time format #{unknown_data}\n"]]
у тебя методы отправки сообщений одинаковые, только меняется статус и текст. передавай их параметром в один общий метод.
так же для формирования ответа используй Rack::Response

2020-12-09 20:02 UTC, BubuntuClu requested changes

2020-12-09 20:02 UTC, BubuntuClu commented on time_formatter.rb
> +    if correct?
дублирующийся код выполняется. сначала в проверке коррект, если не корректный, то о5 такая же проверка и ищется неизвестный формат.

сделай метод `call`, котоырй заполнит правильный и неправильный формат.

и уже эти данные проверяй в `correct?` методе, а не каждый раз считай

2020-12-09 20:02 UTC, BubuntuClu commented on time_formatter.rb
> +          t = Time.now.year
маловероятно но синтаксис у методов объекта может сменится и тогда упадет код. strftime более надежный, так как там общепринятые обозначения времени

2020-12-10 06:53 UTC, sasha370 commented on time_formatter.rb
> +    if correct?
Я не понимаю) 
Зачем вызывать call и потом проверять корректность его выдачи, если можно сначала проверить данные и потом передать их в call

2020-12-10 08:21 UTC, BubuntuClu commented on time_formatter.rb
> +    if correct?
ты результаты проверки не кешируешь и выполняешь логику несколько раз.

ну и такой флоу на мой взгляд логичней - ты выполняешь основное действие сервиса, то зачем он нужен, распарсить параметры. и потом проверяешь удачно ли он распарсил или нет

2020-12-10 08:25 UTC, BubuntuClu approved these changes

2020-12-10 08:25 UTC, BubuntuClu commented on app.rb
> +    time_formatter = TimeFormatter.new(query_data)
```
time_formatter = TimeFormatter.new(query_data)
time_formatter.call

 if time_formatter.success?
    send_response( body: time_formatter.time_string)
else
   send_response(body: "Unknown time format #{time_formatter.unknown_format}\n")
end
```

2020-12-10 08:25 UTC, BubuntuClu commented on time_formatter.rb
> +  def call
из имени метода не понятно что вернется правильная строка

2020-12-10 08:25 UTC, BubuntuClu commented on time_formatter.rb
> +  def convert_time_to_string(data)
в твоем классе это получается приватный метод

2020-12-10 08:42 UTC, sasha370 commented on time_formatter.rb
> +    if correct?
Спасибо, теперь понял. 
видимо лекции по сервисам не до конца донесли зачем они нужны и как и корректно применять )

2020-12-10 10:14 UTC, merged